name = "S2Geometry"
uuid = "64bdcc47-5977-45f9-887c-6c59f4ca8dcb"
authors = ["Tobi Lipede <t.lipede@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
